-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table user_model (
  id                            bigint generated by default as identity not null,
  username                      varchar(255),
  name                          varchar(255),
  surname                       varchar(255),
  city                          varchar(255),
  age                           integer not null,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_user_model primary key (id)
);


-- !Downs

-- drop all
drop table if exists user_model;

