-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table AUTHORS (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  surname                       varchar(255),
  nationality                   varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_authors primary key (id)
);

create table INGREDIENTS (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  family                        varchar(255),
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_ingredients primary key (id)
);

create table RECIPES (
  id                            bigint generated by default as identity not null,
  title                         varchar(255),
  description                   varchar(255),
  duration                      integer,
  author_id                     bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_recipes primary key (id)
);

create table recipe_ingredient (
  recipe_id                     bigint not null,
  ingredient_id                 bigint not null,
  constraint pk_recipe_ingredient primary key (recipe_id,ingredient_id)
);

-- foreign keys and indices
create index ix_recipes_author_id on RECIPES (author_id);
alter table RECIPES add constraint fk_recipes_author_id foreign key (author_id) references AUTHORS (id) on delete restrict on update restrict;

create index ix_recipe_ingredient_recipes on recipe_ingredient (recipe_id);
alter table recipe_ingredient add constraint fk_recipe_ingredient_recipes foreign key (recipe_id) references RECIPES (id) on delete restrict on update restrict;

create index ix_recipe_ingredient_ingredients on recipe_ingredient (ingredient_id);
alter table recipe_ingredient add constraint fk_recipe_ingredient_ingredients foreign key (ingredient_id) references INGREDIENTS (id) on delete restrict on update restrict;


-- !Downs

-- drop all foreign keys
alter table RECIPES drop constraint if exists fk_recipes_author_id;
drop index if exists ix_recipes_author_id;

alter table recipe_ingredient drop constraint if exists fk_recipe_ingredient_recipes;
drop index if exists ix_recipe_ingredient_recipes;

alter table recipe_ingredient drop constraint if exists fk_recipe_ingredient_ingredients;
drop index if exists ix_recipe_ingredient_ingredients;

-- drop all
drop table if exists AUTHORS;

drop table if exists INGREDIENTS;

drop table if exists RECIPES;

drop table if exists recipe_ingredient;

